### ISSUE TITLE
Quick question about how to enable the blur

### ISSUE THREAD

**Issue by yhutter** [L4ki/Shiny-Plasma-Themes#1]
First of all kudos to you for creating such an awesome theme :smile: .
I just have a quick question about how to enable the semi transparent blur theme (showcased in the first screenshot). 
I noticed that under Global Theme / Window Decorations there is a Shiny-Blur-Aurorae option which I believe should enable this effect.

Is there perhaps something I am missing or some other setting I need to check/enable?

**Comment by L4ki** [comment]
Hi Yannick, 

Thank you very much for your support.

 For the BLUR window effect I use Kwin Scripts "Force Blur": https://store.kde.org/p/1294604/ 

For the BLUR effect, you can also use KVANTUM Manager: https://store.kde.org/p/1005410, with some Kvantum Theme 

(for example "Shiny-Kvantum": https://www.pling.com/p/1633316/)

Best regards,

**Comment by yhutter** [comment]
Awesome thanks a lot it works like a charm with Kvantum on Wayland :relaxed:
